### PR TITLE
feat: Support IPv4 only hosts

### PR DESCRIPTION
**Pull request by brettdavis-bmw**
Please let me know what you think of this approach to this feature. We need this pretty immediately in our environment, but I was hoping that we could avoid having to host a fork of this repo just to support this feature since it seems like it was pretty easy to shim in.

# Description

IPv6 is not enabled in our kubernetes cluster network, however we have fluentd-based logging targets that are using UDP exclusively so we'd like to be able to use this sink for those cases. The parameter to selectively turn off the ipv6 dual mode has been added in such a way that it should be backwards compatible with existing configurations of this sink. 

# Checklist

- [X] I have squashed my commits into a single one with a message that aligns with the contributing guidelines
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [O] I have made corresponding changes to the documentation
 Question: There's a remark in the documentation that this only supports dual mode over ipv6, but if we add this feature, do you have any suggestions on how to reword this verbiage?
- [O] I have added tests that prove my fix is effective or that my feature works
 Question: I could use some suggestions regarding how to verify that the app settings are being applied in unit tests. We've tested this in our environment, so we know this'll work but I could use some ideas on how to test that the transport layer is working as intended.

### CODE REVIEW

**Comment by FantasticFiasco** [comment]
Hi and welcome to the project!

Before we start, are you specifying remote address using IP or hostname, and if hostname, does its underlying IP address ever change?

**Comment by brettdavis-bmw** [comment]
Thanks for the warm welcome! The remote address will always be specified with a hostname in our case, never an IP address. This is because have service mesh technologies in place which control the inter-service routing by updating the DNS entries on the containers - this means means the underlying IP is quite likely to change.

**Comment by FantasticFiasco** [comment]
I will be able to provide you with a pre-release on NuGet, but my current priorities prevent me from releasing anything official the coming weeks.

It seems like the IPv4 over IPv6 strategy we've chosen doesn't cover all cases. I need to see what alternatives we have, because either way we go, there is going to be breaking changes. And if so, let's chose the once that are better in the long run, which probably involves more work.

Will a pre-release on NuGet work for you in the short term?

**Comment by brettdavis-bmw** [comment]
Pre-release would definitely be enough for us in the short term. We really appreciate it! It'll definitely make our lives easier not having to maintain a fork and hopefully this option will help any other organizations with similar constraints.

**Comment by FantasticFiasco** [comment]
> I have made corresponding changes to the documentation
Question: There's a remark in the documentation that this only supports dual mode over ipv6, but if we add this feature, do you have any suggestions on how to reword this verbiage?

We'll leave it as is since we only plan for a pre-release for now. The documentation is still true for the latest official release.

> I have added tests that prove my fix is effective or that my feature works
Question: I could use some suggestions regarding how to verify that the app settings are being applied in unit tests. We've tested this in our environment, so we know this'll work but I could use some ideas on how to test that the transport layer is working as intended.

Again, since this is a pre-release and only you will use it, as long as you say it works in your circumstances, we don't need any tests.

**Comment by FantasticFiasco** [comment]
There is a pre-release available on nuget.org called `6.0.0-beta1-6.0.0-beta1-00689`. Sorry about the versioning, the build scripts are not aligned with the workflow :angry: 

Please let me know if your changes are working as expected.

May I call upon you to verify that the next official release works in your circumstances as well, before officially publishing it?

**Comment by brettdavis-bmw** [comment]
Thanks Mattias! Yes I will validate that the pre-release is working as soon as I can, and yes you can definitely call upon us to validate the next release version before officially publishing it. We’re happy to help!

-Brett

**Comment by FantasticFiasco** [comment]
Priorities had me focusing on other issues, but now we have [beta3 available on www.nuget.org](https://www.nuget.org/packages/Serilog.Sinks.UDP/6.0.0-beta3).

Would you be able to validate that the pre-release still conform with your requirements? You will have to make some changes to your configuration of the UDP sink, please see the migration instructions [here](https://github.com/FantasticFiasco/serilog-sinks-udp/blob/master/CHANGELOG.md#dizzy-changed).

**Comment by FantasticFiasco** [comment]
Release v6.0.0 is now live on [nuget.org](https://www.nuget.org/packages/Serilog.Sinks.UDP/6.0.0).

Thank you for reporting the issue!

**Pull request merged**
