### PR TITLE
feat: Migrate project to csproj

### LINKED ISSUE #7: NetStandard 1.3 and csproj migration
### Step 1: Describe your environment

* Develop on OS X and Windows
* Run code on Windows and Ubuntu
  
### Step 2: Describe the problem

I would like to migrate the project to the new csproj format and downgrade the NetStandard reference to 1.3 to match Serilog.  From what I can tell 1.3 is the lowest this library could use due to needing System.Net.Sockets.

### PR DESCRIPTION
**Pull request by scottamartin**
- feat: downgrade from netstandard1.5 to netstandard1.3 and convert project to csproj
- chore: clean up build warnings in the csproj files
- chore: Update appveyor.yml image Visual Studio 2017 and remove install steps to install dotnet cli
- chore: update package information
- chore: remove assembly info generation from csproj
- docs(changelog): update
- chore: update csproj to not reference entire netstandard and reference System.Net.Sockets for netstandard1.3
- chore: treat warnings as errors

closes #7

### CODE REVIEW

**Comment by FantasticFiasco** [comment]
Nice!

I'll start looking at it this evening. Would it possible for you to give me push permissions on your fork? That way I can make code formatting changes without you having to worry about them, I wan't you to focus on the bigger picture and I'll fix the small things.

We'll end with you doing a squash when we're done, making sure you are credited accordingly for your contribution to the project.

**Comment by scottamartin** [comment]
Added.

I was going to ask you about your opinion on keeping the AssemblyInfo.cs or moving it all to the csproj file. That way the build will auto generate it. If you need anything on the build script side and versioning let me know. I actively use CAKE for all of my .NET Core projects to allow for cross platform builds.

**Comment by FantasticFiasco** [comment]
I think we should migrate the information in `AssemblyInfo.cs` to the project file, keeping up with how VS2017 would do it for new projects.

Regarding the build scripts, I shamelessly copied them from the Serilog project when I created this sink back in the days, have no love for them, and encourage the idea of moving to Cake. Would that be something you would like to be involved with since you brought it up? If so, I would propose that we complete this PR and start a new with the goal of incorporating Cake.

**Comment by scottamartin** [comment]
I agree on the AssemblyInfo.  Let me know if you want me to make that change in the fork.

As for CAKE, I agree.  Let's finish this feature and then make changes.  I have a pretty standard CAKE script for clean, restore, build, test, and pack in AppVeyor.

**Comment by scottamartin** [comment]
I need to look into the current build issue as well.

**Comment by FantasticFiasco** [comment]
From my perspective this PR looks splendid. Is there anything more you would like to commit?

Would you me to publish a beta package on nuget.org or do you pick the package from AppVeyor?

**Comment by scottamartin** [comment]
A beta on Nuget would be easier.

I would like to test that to make sure everything is still working as expected.  Also, I would like to figure out how to make the tests run and build on my Mac.  I can't get it to target netstandard1.3, even with the -f option.

**Comment by scottamartin** [comment]
Disregard on the build and run of the test project.  I needed to clean my workspace.

**Comment by FantasticFiasco** [comment]
2.3.0-beta1 has been uploaded to nuget.org.

Please let me know if I can help you in any way with your problems.

**Comment by scottamartin** [comment]
Thanks, I will work on testing this tomorrow morning.

**Comment by FantasticFiasco** [comment]
Thanks for teaming up with me this evening. See you tomorrow.

**Comment by scottamartin** [comment]
I updated this to match the serilog-sinks-periodicbatching csproj, so that a full reference to the NETStandard nuget package is not required.  I also updated the version to 2.3.0-beta2.  Would you be so kind to publish that package as well to Nuget?

**Comment by FantasticFiasco** [comment]
Done

**Comment by scottamartin** [comment]
I have tested 2.3.0-beta2 against a .NET 4.5.2 application (Windows 10) sending logs over UDP to logstash and against a netcoreapp1.1 application (OS X 10.12.4) sending logs over UDP to logstash.  I did not encounter any issues.

**Comment by FantasticFiasco** [comment]
Then we're ready for production! 🍰 

Can you squash all commits, and then I'll rebase it on `master` and release the official 2.3.0.

Out of curiosity I am interested as to why you use UDP and not HTTP for sending logs to logstash. Don't misunderstand the question as criticism, I'm genuinely interested by the decisions that lead to sending the logs using UDP.

**Comment by scottamartin** [comment]
Squash complete.

We went with UDP because we don't want logging to be critical and UDP allows for a fail silent from the applications standpoint.  We have other measures in place to alert us in case logs stop or there is a network issue.  It also makes it easy when running locally to not have the full ELK stack running all of the time.

**Comment by FantasticFiasco** [comment]
Release 2.3.0 is now official on nuget.org.

Thanks for the effort you've put into this contribution. I hope Serilog and the UDP sink will continue to bring value to your products in the future.

**Comment by scottamartin** [comment]
Great, and thank you for the help.

Would you still like to look into build script updates?  If so I can open another issue around that and put together a feature branch over the next week.

**Comment by FantasticFiasco** [comment]
Moving to Cake is the right choice. Open the issue, and if you would like to spilt the workload just tell me. 

You can open a WIP PR to get the scripts exercised on AppVeyor if you want. And no pressure, you can take your time.

**Pull request merged**
