### PR TITLE
feat: add log4net text formatter

### PR DESCRIPTION
**Pull request by jvanrhyn**
Added text formatter compliant with log4net schema, thus compliant with Log4View

### CODE REVIEW

**Comment by FantasticFiasco** [comment]
Hi Johan and welcome to this repository!

This looks perfect! I will take a closer look at it tomorrow, do I have push permissions to your fork? I would like to update the change log, and in the end you will have to squash all commits into a single one, before I merge this back to `master` and create a new release.

Does that sound ok?

**Comment by jvanrhyn** [comment]
Hi. Yes, that sounds fine.

**Comment by FantasticFiasco** [comment]
Can you squash my commit into your, push, and then I'll release a beta NuGet package. You should try it out, and if you feel content with the functionality I'll release it officially.

Thanks for the contribution, this was one of the cleanest PR I've got, it seems that you have an eye for details. Thanks!

**Comment by jvanrhyn** [comment]
Thanks Mattias. I have squashed the commits and will certainly try out the beta of the NuGet package.

**Comment by FantasticFiasco** [comment]
A NuGet package with version 3.3.0-beta-1-00507 is now available on nuget.org. Please let me know if the package behaves as you expect.

**Comment by jvanrhyn** [comment]
Thanks, Mattias. Yes, it is behaving in the way I expect it to.

**Comment by FantasticFiasco** [comment]
3.3.0 is now official

**Pull request merged**
