### PR TITLE
feat(config): allow to use host name for logstash config

### PR DESCRIPTION
**Pull request by marekstachura**

### CODE REVIEW

**Comment by FantasticFiasco** [comment]
Well done! I'll take a look at it tonight.

**Comment by FantasticFiasco** [comment]
Oh, sorry, the CI failed, let me look at it before you squash

**Comment by FantasticFiasco** [comment]
Ok then, I'm all set. Please proceed with your squash.

**Comment by marekstachura** [comment]
OK, squashed!

**Pull request merged**
